---
- hosts: all
  become: yes
  become_user: root
  tasks:
    # some supporting tools
    - apt: name=curl update_cache=yes
    - apt: name=htop

    # # required files
    - file: path=/opt/erlangelist state=directory mode=0755
    - copy: src=remote_files/erlangelist-settings.sh dest=/opt/erlangelist/ mode=0755
    - copy: src=remote_files/docker-helper.sh dest=/opt/erlangelist/ mode=0755

    # disable ssh password login
    - lineinfile: "dest=/etc/ssh/sshd_config create=no line='PasswordAuthentication no'"
    - service: name=ssh state=reloaded

    # don't write systemd to syslog
    - lineinfile: "dest=/etc/systemd/journald.conf create=yes line='ForwardToSyslog=no'"
    - lineinfile: "dest=/etc/systemd/journald.conf create=yes line='Storage=persistent'"

    # iptables log
    - copy: src=remote_files/iptables dest=/etc/logrotate.d/ owner=root group=root
    - copy: src=remote_files/iptables.conf dest=/etc/rsyslog.d/ owner=root group=root
    - service: name=rsyslog state=restarted

    # firewall rules
    - include: tasks/erlangelist_service.yml name=firewall-rules
    - service: name=firewall-rules state=started

    # install docker
    - apt: name=wget
    - apt: name=apt-transport-https
    - apt: name=ca-certificates
    - apt: name=curl
    - apt: name=gnupg2
    - apt: name=software-properties-common
    - stat: path=/usr/bin/docker
      register: docker
    - shell: "curl -sSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -"
      when: docker.stat.exists == false
    - command: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian jessie stable"
      when: docker.stat.exists == false
    - apt: name=docker-ce update_cache=yes
      when: docker.stat.exists == false
    - copy: src=remote_files/docker_daemon.json dest=/etc/docker/daemon.json owner=root group=root
      when: docker.stat.exists == false
    - service: name=docker state=restarted
      when: docker.stat.exists == false

    # install uuid-runtime
    - apt: name=uuid-runtime

    # setup git
    - group: name=git
    - user: name=git group=git groups=docker,sudo shell=/bin/bash
    - file: path=/home/git/.ssh state=directory owner=git group=git mode=0700
    - assemble: remote_src=false src=git_keys dest=/home/git/.ssh/authorized_keys owner=git group=git mode=0600

    # create git repo with post-receive hook
    - stat: path=/home/git/erlangelist.git
      register: erlangelist_repo
    - file: path=/home/git/erlangelist.git state=directory owner=git group=git mode=0700
      when: erlangelist_repo.stat.exists == false
    - become_user: git
      shell: cd /home/git/erlangelist.git && git init . --bare
      when: erlangelist_repo.stat.exists == false
    - copy: src=remote_files/post-receive dest=/home/git/erlangelist.git/hooks/ owner=git group=git mode=0755
    - file: path=/var/log/deploy.log state=touch owner=git group=git
    - lineinfile: "dest=/etc/sudoers.d/post_receive_hook create=yes line='git ALL=(ALL) NOPASSWD: /bin/systemctl' validate='visudo -cf %s'"

    # Erlangelist systemd services
    - include: tasks/erlangelist_service.yml name=erlangelist-site
    - include: tasks/erlangelist_service.yml name=erlangelist-site-firewall
    - include: tasks/erlangelist_service.yml name=erlangelist-backup-site
    - service: name=erlangelist-backup-site enabled=no

    # journald log configuration
    - ini_file:
        dest: "/etc/systemd/journald.conf"
        section: Journal
        option: MaxRetentionSec
        value: "1 week"
        no_extra_spaces: yes
    - ini_file:
        dest: "/etc/systemd/journald.conf"
        section: Journal
        option: SystemMaxUse
        value: "100M"
        no_extra_spaces: yes
    - command: systemctl force-reload systemd-journald
