---
- hosts: all
  sudo: true
  tasks:
    # firewall rules
    - file: path=/opt/erlangelist state=directory mode=0755
    - copy: src=remote_files/firewall-rules.sh dest=/opt/erlangelist mode=0755
    - copy: src=remote_files/firewall-rules.service dest=/lib/systemd/system/
    - service: name=firewall-rules enabled=yes

    # install docker
    - apt: name=wget
    - stat: path=/usr/bin/docker
      register: docker
    - shell: wget -qO- https://get.docker.com/ | sh
      when: docker.stat.exists == false

    # install uuid-runtime
    - apt: name=uuid-runtime

    # setup git
    - group: name=git
    - user: name=git group=git groups=docker,sudo shell=/bin/bash
    - file: path=/home/git/.ssh state=directory owner=git group=git mode=0700
    - assemble: remote_src=false src=git_keys dest=/home/git/.ssh/authorized_keys owner=git group=git mode=0600

    # create git repo with post-receive hook
    - stat: path=/home/git/erlangelist.git
      register: erlangelist_repo
    - file: path=/home/git/erlangelist.git state=directory owner=git group=git mode=0700
      when: erlangelist_repo.stat.exists == false
    - sudo_user: git
      shell: cd /home/git/erlangelist.git && git init . --bare
      when: erlangelist_repo.stat.exists == false
    - copy: src=remote_files/post-receive dest=/home/git/erlangelist.git/hooks/ owner=git group=git mode=0755
    - file: path=/var/log/deploy.log state=touch owner=git group=git

    # collectd
    - apt: name=collectd
    - apt: name=collectd-utils
    - copy: src=remote_files/collectd.conf dest=/etc/collectd/ owner=root group=root mode=0644
    - service: name=collectd state=restarted

    # Erlangelist systemd services
    - copy: src=remote_files/docker-helper.sh dest=/opt/erlangelist/ mode=0755
    - copy: src=remote_files/erlangelist-database.sh dest=/opt/erlangelist/ mode=0755
    - copy: src=remote_files/erlangelist-geoip.sh dest=/opt/erlangelist/ mode=0755
    - copy: src=remote_files/erlangelist-graphite.sh dest=/opt/erlangelist/ mode=0755
    - copy: src=remote_files/erlangelist-site.sh dest=/opt/erlangelist/ mode=0755
    - copy: src=remote_files/erlangelist-database.service dest=/lib/systemd/system/
    - copy: src=remote_files/erlangelist-geoip.service dest=/lib/systemd/system/
    - copy: src=remote_files/erlangelist-graphite.service dest=/lib/systemd/system/
    - copy: src=remote_files/erlangelist-site.service dest=/lib/systemd/system/
    - service: name=erlangelist-database enabled=yes
    - service: name=erlangelist-geoip enabled=yes
    - service: name=erlangelist-graphite enabled=yes
    - service: name=erlangelist-site enabled=yes
    - lineinfile: "dest=/etc/sudoers.d/post_receive_hook create=yes line='git ALL=(ALL) NOPASSWD: /bin/systemctl' validate='visudo -cf %s'"
